spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update           # Permitido solo si generas esquema desde el código, ¿deberíamos safarlo?
    show-sql: false
    # generate-ddl: true        # Se puede eliminar, Hibernate suele generar el DDL automáticamente
  logging:
    level:
      org.hibernate.SQL: OFF
      org.hibernate.orm.jdbc.bind: OFF
      org.hibernate.type.descriptor.sql.BasicBinder: OFF
      # Opcional: mantener otros logs de Hibernate en nivel más alto
      org.hibernate: WARN
  sql:
    init:
      mode: always               # Evita ejecutar data.sql en cada arranque. Inicializar datos me interesa

  datasource:
    url: ${DB_URL} ?createDatabaseIfNotExist=true # útil si te da flojera crear el schema. Usar misma variable que en base, cada entorno define su valor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

https:
  secure: true                # Asegura banderas Secure y HTTPS en cookies

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never     # No exponer detalles de salud en producción

logging:
  file:
    name: /var/log/pdds-backend.log
  level:
    root: INFO
    pe.edu.pucp.inf.pddsbackend: DEBUG
